# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20161214_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kirrurl',
            options={'ordering': ('id',)},
        ),
    ]
