# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20161216_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kirrurl',
            options={},
        ),
    ]
